# --- OpenStreetMap Building Detector configuration file --- #

# | Imagery | #

# Access Key - necessary for downloading certain types of imagery
accessKey: "pk.eyJ1Ijoib3NtLWJ1aWxkaW5nZGV0ZWN0b3IiLCJhIjoiY2swcHZpZjQzMDIzMDNjbXk1aHo3bTI0ciJ9.v_QP3dbWP5C6_BM8LjiwKA"

# Default map location and zoom
start_lat: 40.103232
start_lng: -88.227215
start_zoom: 13

# | OpenStreetMap login information | #
osmUpload:
    # API location. The full v0.6 OpenStreetMap database API is https://api.openstreetmap.org/api/0.6
    # dev server: https://api06.dev.openstreetmap.org
    api: https://api06.dev.openstreetmap.org 
    username: OSM_buildingdetector
    password: fakepassword123
    